name: Update Filter Lists

on:
  schedule:
    - cron: "0 3 * * *"  # Chạy hàng ngày lúc 10:00 sáng (giờ Việt Nam)
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Tự động hủy các workflow cũ khi có workflow mới trên cùng nhánh

env:
  NODE_ENV: production

jobs:
  cgps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Đã cập nhật lên phiên bản mới nhất
        with:
          repository: "tuananh15091993/cloudflare-gateway-pihole-scripts"
          ref: "main"

      - name: Install Node.js
        uses: actions/setup-node@v4  # Đã cập nhật lên phiên bản mới nhất
        with:
          node-version: 'lts/*'     # Sử dụng phiên bản LTS mới nhất, tránh lỗi deprecated

      - name: Install npm dependencies
        run: npm ci

      - name: Download allowlists
        run: npm run download:allowlist
        env:
          ALLOWLIST_URLS: ${{ vars.ALLOWLIST_URLS }}

      - name: Download blocklists
        run: npm run download:blocklist
        env:
          BLOCKLIST_URLS: ${{ vars.BLOCKLIST_URLS }}

      - name: Delete old rules and lists
        run: npm run cloudflare-delete
        continue-on-error: true  # Tiếp tục workflow ngay cả khi bước này thất bại
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_LIST_ITEM_LIMIT: ${{ secrets.CLOUDFLARE_LIST_ITEM_LIMIT }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Create new rules and lists
        run: npm run cloudflare-create
        env:
          BLOCK_PAGE_ENABLED: ${{ vars.BLOCK_PAGE_ENABLED }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_LIST_ITEM_LIMIT: ${{ secrets.CLOUDFLARE_LIST_ITEM_LIMIT }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send ping request (if PING_URL is set)
        if: ${{ secrets.PING_URL != '' }}  # Lệnh này chỉ chạy khi có PING_URL
        run: curl "${{ secrets.PING_URL }}"
